---
name: Update chart version
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  increase-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
        
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: Get changed files in the charts folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v40
        with:
          files: charts/**

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run update for any chart concerned by the commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
         cd hack/ && go run update_after_renovate.go ${{ steps.changed-files-specific.outputs.all_changed_files }}
         git commit -a -m "[AUTO] Update chart version"
         git push
